import { existsSync, mkdirSync, readFileSync, writeFileSync, chmodSync } from "node:fs";
import { homedir } from "node:os";
import { delimiter, dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { optionalEnvFrom } from "../supervisor/bun-cron-service.ts";
import { AUTO_PORT, CONFIG_PATH, DATA_DIR, WORKSPACE_ROOT } from "../paths.ts";

const HERE = dirname(fileURLToPath(import.meta.url));
const CLI_MAIN = resolve(HERE, "main.ts");
const EXPLICIT_CONFIG_PATH = process.env.AUTO_CONFIG;

const IS_WINDOWS = process.platform === "win32";

function shimPath(): string {
  const home = process.env.HOME || process.env.USERPROFILE || homedir();
  if (!home) throw new Error("cannot determine the home directory (HOME is not set)");
  return resolve(home, ".local", "bin", IS_WINDOWS ? "auto.cmd" : "auto");
}

function shellQuote(value: string): string {
  return `'${value.replaceAll("'", `'"'"'`)}'`;
}

export type ShimInput = {
  workspaceRoot: string;
  /** Only exported when the config location was set explicitly. */
  configPath?: string | null;
  dataDir: string;
  port: number;
  bunPath: string;
  cliMain: string;
  optionalEnv?: Record<string, string>;
};

/** POSIX shell shim. */
export function renderShim(input: ShimInput): string {
  // Tiny shell script (NOT a symlink) so it's editable / inspectable.
  return [
    "#!/bin/sh",
    "# auto -- source-install shim (autogenerated by `bun scripts/auto-install.ts`)",
    `export AUTO_HOME=${shellQuote(input.workspaceRoot)}`,
    ...(input.configPath ? [`export AUTO_CONFIG=${shellQuote(input.configPath)}`] : []),
    `export AUTO_DATA_DIR=${shellQuote(input.dataDir)}`,
    `export AUTO_PORT=${shellQuote(String(input.port))}`,
    ...Object.entries(input.optionalEnv ?? {}).map(([k, v]) => `export ${k}=${shellQuote(v)}`),
    `exec ${shellQuote(input.bunPath)} ${shellQuote(input.cliMain)} "$@"`,
    "",
  ].join("\n");
}

/** Windows batch shim (the same settings; `%` is doubled so values are not expanded). */
export function renderCmdShim(input: ShimInput): string {
  const set = (k: string, v: string): string => `set "${k}=${v.replaceAll("%", "%%")}"`;
  return [
    "@echo off",
    "rem auto -- source-install shim (autogenerated by `bun scripts/auto-install.ts`)",
    set("AUTO_HOME", input.workspaceRoot),
    ...(input.configPath ? [set("AUTO_CONFIG", input.configPath)] : []),
    set("AUTO_DATA_DIR", input.dataDir),
    set("AUTO_PORT", String(input.port)),
    ...Object.entries(input.optionalEnv ?? {}).map(([k, v]) => set(k, v)),
    `"${input.bunPath}" "${input.cliMain}" %*`,
    "",
  ].join("\r\n");
}

function currentShimInput(bunPath: string, cliMain: string): ShimInput {
  return {
    workspaceRoot: WORKSPACE_ROOT,
    configPath: EXPLICIT_CONFIG_PATH ? CONFIG_PATH : null,
    dataDir: DATA_DIR,
    port: AUTO_PORT,
    bunPath,
    cliMain,
    optionalEnv: optionalEnvFrom(),
  };
}

/** Is `dir` one of the directories on PATH? */
export function isOnPath(dir: string, pathEnv: string = process.env.PATH ?? ""): boolean {
  const want = resolve(dir);
  return pathEnv.split(delimiter).some((entry) => entry !== "" && resolve(entry) === want);
}

function makeExecutable(path: string): void {
  if (IS_WINDOWS) return; // .cmd files need no mode bit
  try {
    chmodSync(path, 0o755);
  } catch {
    // best-effort
  }
}

export type InstallShimResult = {
  path: string;
  action: "created" | "updated" | "unchanged";
  /** Whether the shim's directory is on PATH (when false, `auto` will not be found by name). */
  onPath: boolean;
};

export function installShim(): InstallShimResult {
  const target = shimPath();
  const bunPath = process.execPath;
  const input = currentShimInput(bunPath, CLI_MAIN);
  const desired = IS_WINDOWS ? renderCmdShim(input) : renderShim(input);
  const onPath = isOnPath(dirname(target));

  mkdirSync(dirname(target), { recursive: true });

  if (existsSync(target)) {
    let current = "";
    try {
      current = readFileSync(target, "utf8");
    } catch {
      current = "";
    }
    if (current === desired) {
      // Make sure mode is right even if content matches.
      makeExecutable(target);
      return { path: target, action: "unchanged", onPath };
    }
    process.stderr.write(`auto: overwriting existing shim at ${target}\n`);
    writeFileSync(target, desired);
    makeExecutable(target);
    return { path: target, action: "updated", onPath };
  }

  writeFileSync(target, desired);
  makeExecutable(target);
  return { path: target, action: "created", onPath };
}

if (import.meta.main) {
  try {
    const result = installShim();
    process.stdout.write(`shim ${result.action} at ${result.path}\n`);
    if (!result.onPath) {
      process.stderr.write(`note: ${dirname(result.path)} is not on your PATH; add it to run \`auto\` by name\n`);
    }
  } catch (err) {
    const msg = err instanceof Error ? err.message : String(err);
    process.stderr.write(`shim install failed: ${msg}\n`);
    process.exit(1);
  }
}
